import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Jimbaux",
  description: "Generated by create next app",
};

function HeaderAnimation() {
  return (
    <div className="absolute pointer-events-none -top-24 flex -rotate-45 justify-between aurora scale-150 opacity-20">
      <div className="flex gap-20">
        <div className="h-96 w-16 bg-pink-500 scale-150 -rotate-45"></div>
        <div className="h-96 w-16 bg-red-500 scale-150 -rotate-45"></div>
        <div className="h-96 w-16 bg-yellow-500 scale-150 -rotate-45"></div>
        <div className="h-96 w-16 bg-green-500 scale-150 -rotate-45"></div>
        <div className="h-96 w-16 bg-blue-500 scale-150 -rotate-45"></div>
      </div>
    </div>
  )
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body>
        <main className="flex flex-col justify-center items-center relative overflow-hidden">
          <HeaderAnimation />
          {children}

        </main>
      </body>
    </html>
  );
}
